#!/bin/sh
# When you change these, don't forget to update the SystemD user environment
# files under .config/environment.d/
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export _JAVA_AWT_WM_NONREPARENTING=1
export EDITOR=nvim
export TERMINAL=ghostty

# Setup rustup
. "$HOME/.cargo/env"


# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
