#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=10000

# prompt
BLUE="\[$(tput setaf 4)\]"
MAGE="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
RESET="\[$(tput sgr0)\]"
export PS1="\n ${BLUE}\u${MAGE}@${BLUE}\h ${CYAN}\w${RESET} \n :3 "

# directory-dependent tools
PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# completion
eval "$(fzf --bash)"

if [[ -x "$HOME/.local/bin/aws_completer" ]]; then
    complete -C "$HOME/.local/bin/aws_completer" aws
fi

# Homebrew
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"

    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            if [[ -r "${COMPLETION}" ]]; then
                source "${COMPLETION}"
            fi
        done
    fi
fi

alias bw="flatpak run --command=bw com.bitwarden.desktop"

if type mise &>/dev/null; then
    eval "$(mise activate bash)"
fi
