#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=10000

# prompt
BLUE="\[$(tput setaf 4)\]"
MAGE="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
RESET="\[$(tput sgr0)\]"
export PS1="\n ${BLUE}\u${MAGE}@${BLUE}\h ${CYAN}\w${RESET} \n :3 "

# completion
eval "$(fzf --bash)"
. <(asdf completion bash)

daily_commits() {
  git log \
    --since=midnight \
    --author="$(git config --get user.email)" \
    --format=%s
}

# Aliases
alias d="docker"
alias dc="docker compose"
alias dcrm="docker compose -p crm -f ~/Work/crm/development/bind-compose.yml"
