#!/bin/bash

# Source ~/.profile if present, bash won't otherwise
if [ -f "$HOME/.profile" ]; then
    source "$HOME/.profile"
fi

# Detect MacOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    # Silence complaints about not using zsh
    export BASH_SILENCE_DEPRECATION_WARNING=1

    # If we're on an interactive login terminal on MacOS, bash won't get a
    # chance to load ~/.bashrc, so we'll do it here.
    if [[ $- == *i* && -f "$HOME/.bashrc" ]]; then
        source "$HOME/.bashrc"
    fi
fi

# The following section is mirrored in ~/.zshenv

# Detect Homebrew and use its environment
if type brew &>/dev/null; then
    eval "$(brew shellenv bash)"

    # Add Homebrew's coreutils to PATH
    if [ -d "$(brew --prefix)/opt/coreutils/libexec/gnubin" ]; then
        export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH";
    fi
fi

if [ -f "$HOME/.local/etc/ssl/cert.pem" ]; then
    # Feed Python custom certificates
    export SSL_CERT_FILE="$HOME/.local/etc/ssl/cert.pem"
    export SSL_CERT_DIR="$HOME/.local/etc/ssl/certs"
    export REQUESTS_CA_BUNDLE="$HOME/.local/etc/ssl/cert.pem"

    # Feed cURL custom certificates
    # export CURL_CA_BUNDLE="$SSL_CERT_FILE"

    # Feed Node custom certificates
    export NODE_EXTRA_CA_CERTS="$HOME/.local/etc/ssl/cert.pem"
fi
