#!/usr/bin/env python
"""Cleanup stopped containers and their images
"""

import docker


def szfmt(bytes, units=["B", "KiB", "MiB", "GiB", "TiB"]):
    """ Returns a human readable string reprentation of bytes"""
    return str(bytes) + units[0] if bytes < 1024 else szfmt(bytes >> 10, units[1:])


def prune(client, object_type):
    result = getattr(client, object_type).prune()
    print(
        "Deleted {} {}, reclaimed {}".format(
            len(result[object_type.capitalize() + "Deleted"] or []),
            object_type,
            szfmt(result["SpaceReclaimed"]),
        )
    )


if __name__ == "__main__":
    client = docker.from_env()
    prune(client, "containers")
    prune(client, "images")
    dangling = client.images.list(filters={"dangling": True})
    print(f"Deleting {len(dangling)} dangling images")
    for image in dangling:
        client.images.remove(image.id)
    print("Done!")
