#!/usr/bin/env python
"""Quickly select OpsWorks instances to ssh into
"""

import sys
import os
import boto3
import subprocess

login_name = {
    'stripes': 'javier',
    'buffalo': 'javiermaldonado',
}


def get_profiles():
    return [{'name': profile, 'client': get_client(profile)}
            for profile in ["stripes", "buffalo"]]


def get_stacks(profile):
    return [{'name': stack['Name'].lower(), 'id': stack['StackId']}
            for stack in profile['client'].describe_stacks()['Stacks']]


def get_instances(profile, stack):
    return profile['client'].describe_instances(StackId=stack['id'])['Instances']


def get_client(profile):
    return boto3.Session(profile_name=profile).client('opsworks')


def full_name(stack, instance):
    return stack['name'] + '/' + instance['Hostname']


def conn_info(profile, instance):
    if 'PublicIp' in instance:
        return {
            'login': login_name[profile['name']],
            'ip': instance['PublicIp']
        }

if __name__ == "__main__":
    query = []
    if len(sys.argv) > 1:
        query = ["-q", sys.argv[1]]

    idfile = os.getenv("OPSWORKS_SSH_KEY")
    if idfile == None:
        print("Failed to find identity file path in environment")
        print("Set the path to your identity file in OPSWORKS_SSH_KEY")
        sys.exit(1)

    instances = {
        full_name(stack, instance): conn_info(profile, instance)
        for profile in get_profiles()
        for stack in get_stacks(profile)
        for instance in get_instances(profile, stack)
        if conn_info(profile, instance)
    }

    instance_list = "\n".join(instances.keys())

    proc = subprocess.run(
        ["fzf", "-1"] + query,
        stdout=subprocess.PIPE,
        input=instance_list,
        encoding="utf8")

    if proc.returncode == 1 or proc.stdout == "":
        print("Failed to find a match")
        sys.exit(1)
    else:
        instance = instances[proc.stdout[:-1]]
        os.execvp("ssh", ["ssh",
                          "-i", idfile,
                          "-l", instance['login'],
                          instance['ip']])
